name: Go

on: [ push, pull_request ]

jobs:

  Lint_Build_Test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17.x
        
    - name: Lint
      run: $GITHUB_WORKSPACE/lint.sh

#    - name: Test
#      run:  export MY_PATH=$(echo $GITHUB_REF | awk -F/ '{print $NF}') && cd $MY_PATH  && go test .
#
#    - name: Build
#      run: export MY_PATH=$(echo $GITHUB_REF | awk -F/ '{print $NF}') && cd $MY_PATH  && go build .
