name: Go

on: [ push, pull_request ]

jobs:

  Lint_Build_Test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17.x
        
    - name: Lint
      run: $GITHUB_WORKSPACE/lint.sh
#     run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.43.0 && export MY_PATH=$(echo $GITHUB_REF | awk -F/ '{print $NF}') && cd $MY_PATH  && golangci-lint run -c $GITHUB_WORKSPACE/.golangci.yml -v
    - name: Test
      run : $GITHUB_WORKSPACE/test.sh
#      run:  export MY_PATH=$(echo $GITHUB_REF | awk -F/ '{print $NF}') && cd $MY_PATH  && go test .
    - name: Build
      run : $GITHUB_WORKSPACE/build.sh    
#      run: export MY_PATH=$(echo $GITHUB_REF | awk -F/ '{print $NF}') && cd $MY_PATH  && go build .
